version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: placessystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    volumes:
      - ./database:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    command: php artisan test
